CREATE SEQUENCE tipo_localidade_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE tipo_localidade (
	id BIGINT GENERATED BY DEFAULT AS SEQUENCE tipo_localidade_seq PRIMARY KEY,
	nome varchar(50) NULL,
	reference varchar(50) NULL,
	codigo varchar(50) NULL
)