CREATE SEQUENCE bairro_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE bairro (
	id BIGINT GENERATED BY DEFAULT AS SEQUENCE bairro_id_seq PRIMARY KEY,
	localidade_id int NOT NULL,
	nome varchar(72) NOT NULL,
	nome_abreviado varchar(36) NULL,
	FOREIGN KEY (localidade_id) REFERENCES localidade(id)
)