CREATE SEQUENCE tipo_logradouro_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE tipo_logradouro (
	id BIGINT GENERATED BY DEFAULT AS SEQUENCE tipo_logradouro_seq PRIMARY KEY,
	nome varchar(50) NULL,	
	codigo varchar(50) NULL
);