CREATE SEQUENCE logradouro_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE logradouro (
	id BIGINT GENERATED BY DEFAULT AS SEQUENCE logradouro_id_seq PRIMARY KEY,
	ufe varchar(2) NOT NULL,
	localidade_id int NOT NULL,
	nome_abreviado varchar(70) NOT NULL,
	nome varchar(125) NOT NULL,
	bairro_inicio_id int NOT NULL,
	bairro_fim_id int NULL,
	cep varchar(16) NOT NULL,
	complemento varchar(100) NULL,
	status_tipo_log varchar(1) NOT NULL,
	nome_sem_acento varchar(70) NOT NULL,
	correio varchar(1) NULL,
	referencia varchar(1) NULL,
	tipo_logradouro_id int NULL,
	bairro varchar(100) NULL,
	localidade varchar(100) NULL
);